### PR TITLE
pass value_scale to the LearnerND's loss_per_simplex function

### PR DESCRIPTION
**Pull request by basnijholt**
Currently, the `LearnerND` cannot access the unscaled value in the `loss_per_simplex`.

This PR fixes this by passing the scale. This fixes a regression introduced when we added scaling.

Now the following code:
```python
import numpy as np
import adaptive
adaptive.notebook_extension()

def isoline_loss_function(y_iso, sigma, priority=1):
    from adaptive.learner.learnerND import default_loss

    def gaussian(x, mu, sigma):
        return np.exp(-(x - mu) ** 2 / sigma ** 2)

    def loss(simplex, values, value_scale):
        distance = np.mean([abs(y_iso * value_scale - y) for y in values])
        return priority * gaussian(distance, 0, sigma) + default_loss(simplex, values, value_scale)

    return loss

level = 0.5
loss = isoline_loss_function(y_iso=level, sigma=1, priority=0.3)

def f(xy):
    x, y = xy
    return x ** 2 + y ** 2 / 2 + y ** 3

learner = adaptive.LearnerND(
    f,
    bounds=[(-1, 1), (-1, 1)],
    loss_per_simplex=loss,
)

adaptive.runner.simple(learner, goal=lambda l: l.npoints > 1000)
%opts Image [colorbar=True]
learner.plot_isoline(level, tri_alpha=0.3)
```

produces
image

instead of 

image

### CODE REVIEW

**Comment by jbweston** [comment]
Seems ok, don't know why tests are failing

**Comment by jbweston** [comment]
@basnijholt the test failures are genuine. 

```
>      loss_curvature = triangle_loss(simplex, values, neighbors, neighbor_values)
E       TypeError: triangle_loss() missing 1 required positional argument: 'neighbor_values'
```

Threre may be others

**Comment by basnijholt** [comment]
Thanks! I've already pushed a fix.

**Comment by basnijholt** [comment]
@jbweston merge if you are OK with this 👍

**Pull request merged**
