### PR TITLE
Add logo to the documentation

### PR DESCRIPTION
**Pull request by basnijholt**
This adds a logo to the documentation.

`python logo.py` generates the image.

Alternatively, we could also generate the logo in CI.

image

### CODE REVIEW

**Comment by jbweston** [comment]
LGTM! Maybe consider adding a comment about how to run the script (i.e. make sure to run as `./logo.py` from the documentation directory)

**Comment by jbweston** [comment]
We should also automatically re-run when `logo.py` changes. I didn't manage to fine the right incantation for the makefile yet.

**Comment by basnijholt** [comment]
Great that you like it Joe!

@akhmerov actually thought that we should pick something with just a random bunch of points such that the triangulation can be seen better. However, I don't agree with that, Adaptive is not about triangulation but about "learning" a function, so I think the logo should represent that. The circle is very recognizable and I think it represents the concept of Adaptive really well.

**Comment by jbweston** [comment]
> Adaptive is not about triangulation but about "learning" a function, so I think the logo should represent that.

The circle logo has grown on me also.

I'll wait for the checks to complete and then merge

**Comment by jbweston** [comment]
The failure has nothing to do with the change so I'm tempted to just merge anyway.

**Pull request merged**
