### PR TITLE
Replace deprecated numpy aliases

### PR DESCRIPTION
**Pull request by eendebakpt**
## Description

Numpy 2.0 is to be released soon (see https://github.com/numpy/numpy/issues/24300#issuecomment-2125643448) and that release will remove a couple of deprecated aliases.

In this PR replace the aliases by the entries suggested by ruff (see https://docs.astral.sh/ruff/rules/numpy2-deprecation/)

## Checklist

- [x] Fixed style issues using `pre-commit run --all` (first install using `pip install pre-commit`)
- [ ] `pytest` passed

## Type of change

*Check relevant option(s).*

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] (Code) style fix or documentation update
- [ ] This change requires a documentation update

### CODE REVIEW

**Review by akhmerov — APPROVED** [review]

**Comment by eendebakpt** [comment]
@akhmerov Tests are passing locally, not sure what is happening to the CI

**Comment by basnijholt** [comment]
Thanks a lot! I think we first need to merge #404 to get the tests to pass. I'll do that in a few hours.

**Comment by jakirkham** [comment]
Thanks all! 🙏

Would it make sense to do a new release with these changes? Or are there other steps still needed before releasing?

**Comment by basnijholt** [comment]
@jakirkham I just released [1.3.0](https://github.com/python-adaptive/adaptive/releases/tag/v1.3.0) :tada:

**Comment by jakirkham** [comment]
Congratulations and thank you again! 🥳 🙏

**Review by Jose1654 — APPROVED** [review]

**Pull request merged**
