### PR TITLE
add a changelog

### PR DESCRIPTION
**Pull request by jbweston**
We move fast and break things. For everyone's sanity it would be good to keep a changelog where we document what stuff we added, fixed and changed.

## TODO
+ [x] Add changelog entries for the previous releases  (using the release notes)
+ [ ] Add changelog entry for the unreleased changes
+ [ ] Add the sphinx [versionadded](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-versionadded) directive to relevant docstrings so that we know when stuff was added.

### CODE REVIEW

**Comment by basnijholt** [comment]
The changes are documented to some degree [here](https://github.com/python-adaptive/adaptive/releases).

**Comment by jbweston** [comment]
> The changes are documented to some degree [here](https://github.com/python-adaptive/adaptive/releases).

That's where we'll get the information to help with bullet point (1), but it is useful to keep this information in the repository because then we can do things like add it to the documentation

**Comment by basnijholt** [comment]
I've added the entries from https://github.com/python-adaptive/adaptive/releases.

I think we can already merge this and open issues for the other two points @jbweston brought up.

**Comment by jbweston** [comment]
@basnijholt do you mind if I fixup the changelog to separate the issues solved into bugfixes and features, in order to conform to the KeepAChangelog format?

**Comment by jbweston** [comment]
:+1: on making the other 2 things separate issues

**Comment by basnijholt** [comment]
I am going to go ahead and merge this. 

@jbweston, the things you wanted to fix, we can always do later. Having _any_ changelog is more valuable than not having it.

**Comment by basnijholt** [comment]
See https://github.com/python-adaptive/adaptive/issues/306.

**Pull request merged**
